name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - main

jobs:
  label-gh-pages-pr:
    runs-on: ubuntu-latest
    if: github.head_ref == 'gh-pages'
    steps:
      - name: Label PRs from gh-pages
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['do-not-merge', 'automated-build']
            })
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '⚠️ **ATTENTION**: This PR is from the `gh-pages` branch which contains automated build output only. This should NOT be merged into the main codebase.'
            })
